version: 2.1

jobs:
  build:
    docker:
      - image: circleci/ruby:3.0.0-node-browsers
        environment:
          LOCAL_PG_USERNAME: root
          POSTGRES_DB: bookstore_test
          LOCAL_PG_PASSWORD: root
      - image: circleci/postgres:latest
        environment:
          POSTGRES_USER: root
          POSTGRES_DB: bookstore_test
          POSTGRES_PASSWORD: root
    steps:
      - checkout
      - run: gem install rails -v 7.0.0
      - run: gem install bundler:2.4.7
      - run: bundle install
      - run: yarn install
      - run: rails db:create db:migrate RAILS_ENV=test
      - run: bundle exec rspec

workflows:
  version: 2
  build-and-test:
    jobs:
      - build
      