version: 2.1

jobs:
  build:
    docker:
      - image: circleci/postgres:13.3-alpine
        environment:
          POSTGRES_USER: root
          POSTGRES_PASSWORD: root
      - image: circleci/ruby:3.0.0-node-browsers
    working_directory: ~/repo
    steps:
      - checkout
      - run:
          name: Install yarn and esbuild
          command: |
            sudo npm install -g yarn
            sudo npm install -g esbuild
      - run:
          name: Install dependencies
          command: |
            bundle install --jobs=4 --retry=3
            yarn install
      - run:
          name: Setup test database
          command: |
            bundle exec rails db:create RAILS_ENV=test
            bundle exec rails db:migrate RAILS_ENV=test
      - run:
          name: Run tests
          command: |
            bundle exec rspec
          environment:
            RAILS_ENV: test
            NODE_ENV: test
      - store_artifacts:
          path: ~/repo/tmp/screenshots/
          destination: screenshots

workflows:
  version: 2.1
  build:
    jobs:
      - build
