version: 2.1

jobs:
  build:
    docker:
      - image: circleci/ruby:3.0.0-node-browsers
        environment:
          POSTGRES_USER: root
          POSTGRES_DB: bookstore_test
          POSTGRES_PASSWORD: abcd1234
      - image: circleci/postgres:latest
        environment:
          POSTGRES_USER: root
          POSTGRES_DB: bookstore_test
          POSTGRES_PASSWORD: abcd1234
    steps:
      - checkout
      - run: gem install rails -v 7.0.0
      - run: gem install bundler:2.4.7
      - run: bundle install
      - run: yarn install
      - run: echo "bb0aca5686c48290d3293afaeedbf7a7" > config/master.key
      - run: cat config/master.key
      - run: rails db:create db:migrate RAILS_ENV=test
      - run: bundle exec rspec
      - store_artifacts:
          path: public/coverage
          destination: coverage

workflows:
  version: 2
  build-and-test:
    jobs:
      - build