default: &default
  adapter: postgresql
  encoding: unicode
  pool: 5
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  host: localhost
  database: bookstore_development
  username: <%= ENV['LOCAL_PG_USERNAME'] %>
  password: <%= ENV['LOCAL_PG_PASSWORD'] %>
  pool: 5

test:
  <<: *default
  host: localhost
  database: bookstore_test
  username: <%= ENV['LOCAL_PG_USERNAME'] %>
  password: <%= ENV['LOCAL_PG_PASSWORD'] %>
  pool: 5

production:
  <<: *default
  database: bookstore_production
  username: bookstore
  password: <%= ENV["BOOKSTORE_DATABASE_PASSWORD"] %>
  pool: 5
